[tool.black]
line-length = 119
required-version = "21.6b0"

[tool.isort]
profile = "black"
line_length = 119
combine_as_imports = true
combine_star = true
known_local_folder = ["arguments", "test_utils", "tests", "utils"]

[tool.mypy]
plugins = [
  "numpy.typing.mypy_plugin",
  "pydantic.mypy"
]
ignore_missing_imports = true
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
strict_optional = false
no_implicit_optional = true
implicit_reexport = true
allow_untyped_globals = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
